### ISSUE TITLE
Please develop payment note function

### ISSUE THREAD

**Issue by vcexnet** [Sandokaaan/EarthCoin2019#4]
Please develop payment note function,This is very important for the development of EAC.please！！

**Comment by Sandokaaan** [comment]
Hello.

The source code updated!

The transaction messages (stored in the blockchain) can be now sent also from the new windows wallet:
https://github.com/Sandokaaan/EarthCoin2019/releases/tag/v.2.0.2

TODO: show the transaction messages in the windows wallet.
For now, only way to show a transaction message is command line function "getrawmessage".

Please, test is, and let me know if it meets your requirements. Or specify, what you need to be improved.

Best regards!
S.
