### ISSUE TITLE
Thank you,please update macos version

### ISSUE THREAD

**Issue by vcexnet** [Sandokaaan/EarthCoin2019#5]
Think you!please update macos version,this is very important.Because of the Mac OS wallet, there is no message option when sending.

In addition, please improve the API function as soon as possible, so that the function of eacpay will be more smooth

**Comment by Sandokaaan** [comment]
Hello.
All my API servers now shows transaction messages correctly. See:
http://explorer.deveac.com:7000/getrawtransaction?t=684e9637a1d14b0cb47e084cb42a7659e5d5fd710ffba9056bab109df211ce27&d=1
http://api.deveac.com/api/tx/684e9637a1d14b0cb47e084cb42a7659e5d5fd710ffba9056bab109df211ce27
http://bck.deveac.com:3000/tx/684e9637a1d14b0cb47e084cb42a7659e5d5fd710ffba9056bab109df211ce27

Look for the field "txComment".

Building of Mac OS wallet is now in a progress, will be ready for download a day later.

**Comment by Sandokaaan** [comment]
Binary builds updated. Now you can download also a version for Mac OSX. See:
https://github.com/Sandokaaan/EarthCoin2019/releases/tag/v.2.0.2

Transaction comments (messages stored in the blockchain) are be shown also in a gui-wallet.

**Comment by vcexnet** [comment]
think you！
